language: node_js
dist: trusty
node_js:
  - "9"

before_install:
  - export TZ=Asia/Shanghai
  - chmod +x ./deploy.sh
  - cd hexo
  - npm install hexo-cli -g

install:
  - npm install

script:
  - hexo clean && hexo g && gulp

after_script:
  - cd ..
  - ./deploy.sh
  
branches:
  only:
    - source
    
cache:
  directories:
    - hexo/node_modules

